image:
  repository: quay.io/mittwald/harbor-operator
  # if no tag is given, the helm-chart's appVersion is used
  # tag: latest
  pullPolicy: Always
  pullSecret: {}

envFrom:
#  - configMapRef:
#      name: env-from-configmap

env:
  helmClientRepositoryCachePath: /tmp/.helmcache
  helmClientRepositoryConfigPath: /tmp/.helmrepo

serviceMonitor:
  enabled: true

metricsPort: 8080

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

nameOverride: {}

fullnameOverride: {}

installHarborChartRepo: true

instances: ~
#  - name: test-harbor
#    type: manual
#    version: v1.8.0
#    wait: true
#    garbageCollection:
#      cron: "0 * * * *"
#      scheduleType: "Hourly"
#
#    users:
#      - name: harbor-user
#        realname: "Harbor User"
#        email: harbor.user@example.com
#        sysAdmin: true
#        password: my-secret-password
#
#    projects:
#      - name: projects
#        storageLimit: 10
#        proxyCacheRegistryName: test-harbor-test-registry # <instanceName>-<registry-name>
#        metadata:
#          enableContentTrust: false
#          autoScan: true
#          severity: "none"
#          reuseSysCVEAllowlist: false
#          public: false
#          preventVul: false
#
#    registries:
#      - name: test-registry
#        parentInstance:
#          name: test-harbor
#        type: docker-hub
#        url: https://hub.docker.com
#        insecure: false
#        credential:
#          secretRef:
#            name: test-harbor-test-registry-creds
#          secretKeyAccessKey: accessKey
#          secretKeyAccessSecret: accessSecret
#          type: basic
#
#    replications:
#      - name: test-replication-src
#        parentInstance:
#          name: test-harbor
#        replicateDeletion: false
#        override: true
#        enabled: true
#        srcRegistryName: test-registry
#        triggerAfterCreation: false
#        filters:
#          - type: name
#            value: alpine
#          - type: tag
#            value: latest
#
#    values: # harbor helm-chart values
#      harborAdminPassword: my-admin-secret
#      externalURL: https://harbor.domain

serviceAccount:
  name: {}
  create: true
