{{- range $instance := .Values.instances }}
  {{- range $repo := .repositories }}
apiVersion: registries.mittwald.de/v1alpha1
kind: Repository
metadata:
  name: {{ $instance.name }}-{{ $repo.name }}
  labels:
    {{- include "chart.labels" $ | nindent 4 }}
spec:
  parentInstance:
    name: {{ $instance.name }}
  name: {{ $repo.name }}
  metadata:
    {{- with $repo.metadata }}
    {{- toYaml . | nindent 4 }}
    {{- end }}

  {{- with $repo.memberRequests }}
  memberRequests:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
  {{- end }}
{{- end }}
