# permissions for end users to edit registries.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: registry-editor-role
rules:
- apiGroups:
  - registries.mittwald.de
  resources:
  - registries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - registries.mittwald.de
  resources:
  - registries/status
  verbs:
  - get
