# permissions for end users to view replications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: replication-viewer-role
rules:
- apiGroups:
  - registries.mittwald.de
  resources:
  - replications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - registries.mittwald.de
  resources:
  - replications/status
  verbs:
  - get
