# permissions for end users to edit replications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: replication-editor-role
rules:
- apiGroups:
  - registries.mittwald.de
  resources:
  - replications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - registries.mittwald.de
  resources:
  - replications/status
  verbs:
  - get
