
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - registries.mittwald.de
  resources:
  - instancechartrepositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - registries.mittwald.de
  resources:
  - instancechartrepositories/status
  verbs:
  - get
  - patch
  - update
