apiVersion: registries.mittwald.de/v1alpha2
kind: Project
metadata:
  name: repository-1
  namespace: harbor-operator
spec:
  memberRequests:
  - role: ProjectAdmin # one of "ProjectAdmin", "Developer", "Guest" or "Master"
    user:
      name: "harbor-user" # reference to a user object
  storageLimit: -1 # storage quota in GB
  name: harbor-project
  parentInstance:
    name: test-harbor
    # All project metadata fields but 'public' are optional
  metadata:
    public:                 false
#    enableContentTrust:     false
#    autoScan:               false
#    severity:               "none"
#    reuseSysCVEAllowlist:   false
#    preventVul:             false