apiVersion: registries.mittwald.de/v1alpha1
kind: InstanceChartRepo
metadata:
  name: harbor # use this name as prefix for your chart (myrepo/mychart)
  namespace: harbor-operator
spec:
  url: https://helm.goharbor.io
  secretRef:
    name: harbor-instancechartrepo-secret