# Replication example with a source registry
# Using a source registry equals using the 'Pull-based' option for 'Replication Mode'
# This pulls the specified resources from the remote registry to the local registry
# Filters and triggers are optional
apiVersion: registries.mittwald.de/v1alpha1
kind: Replication
metadata:
  name: test-replication-src
  namespace: harbor-operator
spec:
  name: test-replication-src
  parentInstance:
    name: test-harbor
  deletion: false
  override: true
  enabled: true
  triggerAfterCreation: true
  srcRegistry: # you have to create the srcRegistry via a registry custom resource first
    name: test-registry-local
#  filters:
#    - type: name
#      value: alpine
#    - type: tag
#      value: latest
#  trigger:
#    type: manual
#    triggerSettings:
#      cron: ""
