apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: instance-viewer-role
rules:
- apiGroups:
  - registries.mittwald.de
  resources:
  - instances
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - registries.mittwald.de
  resources:
  - instances/status
  verbs:
  - get
