name: Verify code generation integrity

on: pull_request

jobs:
  verify-operator-sdk:
    name: Verify Code Generation
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.20.1
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.1
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v3

      - name: Generate manifests
        run: make generate

      - name: Test diff
        run: |
          git diff | cat
          git status --porcelain=v1
          test $(git status --porcelain=v1 | wc -l) -eq 0
